package com.mycompany.smartwallet_silvia;


import com.mycompany.smartwallet_silvia.dao.TransactionDAO;
import com.mycompany.smartwallet_silvia.model.Transaction;
import java.util.List;
import java.util.ArrayList;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;



public class DashboardPanel extends javax.swing.JPanel {
    /**
     * Creates new form JPanel
     */
    
    private int userId;
    
   public DashboardPanel(int userId) {
    this.userId = userId;

    initComponents();
    initializeOriginalModel();
    initializeFields();
    loadTransactionsFromDB();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        ConvertCurrency = new javax.swing.JButton();
        ShowChart = new javax.swing.JButton();
        AddTransaction = new javax.swing.JButton();
        RemoveTransaction = new javax.swing.JButton();
        Income = new javax.swing.JTextField();
        Expense = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        ShowIncome = new javax.swing.JButton();
        ShowExpense = new javax.swing.JButton();
        ShowAll = new javax.swing.JButton();
        FilterByDate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        EditTransaction = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");

        ConvertCurrency.setText("Convert Currency");
        ConvertCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertCurrencyActionPerformed(evt);
            }
        });

        ShowChart.setText("Show Chart");
        ShowChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowChartActionPerformed(evt);
            }
        });

        AddTransaction.setBackground(new java.awt.Color(41, 128, 185));
        AddTransaction.setForeground(new java.awt.Color(255, 255, 255));
        AddTransaction.setText(" Add Transaction  ");
        AddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTransactionActionPerformed(evt);
            }
        });

        RemoveTransaction.setBackground(new java.awt.Color(231, 91, 102));
        RemoveTransaction.setForeground(new java.awt.Color(255, 255, 255));
        RemoveTransaction.setText("Remove Transaction");
        RemoveTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTransactionActionPerformed(evt);
            }
        });

        Income.setEditable(false);
        Income.setBackground(new java.awt.Color(220, 216, 217));
        Income.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Income.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Income.setText("Income");
        Income.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Expense.setEditable(false);
        Expense.setBackground(new java.awt.Color(220, 216, 217));
        Expense.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Expense.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Expense.setText("Expense");
        Expense.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Total.setEditable(false);
        Total.setBackground(new java.awt.Color(220, 216, 217));
        Total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.setText("Total");
        Total.setToolTipText("");
        Total.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ShowIncome.setBackground(new java.awt.Color(220, 216, 217));
        ShowIncome.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        ShowIncome.setText("Show Income");
        ShowIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowIncomeActionPerformed(evt);
            }
        });

        ShowExpense.setBackground(new java.awt.Color(220, 216, 217));
        ShowExpense.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        ShowExpense.setText("Show Expenses");
        ShowExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowExpenseActionPerformed(evt);
            }
        });

        ShowAll.setBackground(new java.awt.Color(220, 216, 217));
        ShowAll.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        ShowAll.setText("Show All");
        ShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllActionPerformed(evt);
            }
        });

        FilterByDate.setBackground(new java.awt.Color(220, 216, 217));
        FilterByDate.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        FilterByDate.setText("Filter By date");
        FilterByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterByDateActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Table);
        Table.getAccessibleContext().setAccessibleName("");

        EditTransaction.setBackground(new java.awt.Color(94, 192, 122));
        EditTransaction.setForeground(new java.awt.Color(255, 255, 255));
        EditTransaction.setText("Edit Transaction");
        EditTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ShowIncome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowExpense)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShowAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(FilterByDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShowChart)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Expense, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RemoveTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ConvertCurrency))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(ShowChart)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddTransaction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Expense)
                    .addComponent(Income)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RemoveTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FilterByDate)
                    .addComponent(ShowAll)
                    .addComponent(ShowExpense)
                    .addComponent(ShowIncome)
                    .addComponent(ConvertCurrency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

     private void initializeOriginalModel() {
        String[] columnNames = {"Type", "Description", "Amount", "Date"};
    originalModel = new javax.swing.table.DefaultTableModel(new Object[][]{}, columnNames);
    Table.setModel(originalModel);
    }
     
     private void initializeFields() {
    Income.setText("Income: 0.00");
    Expense.setText("Expense: 0.00");
    Total.setText("Total: 0.00");
}
    
    private void AddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTransactionActionPerformed
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Table.getModel();

    String type = javax.swing.JOptionPane.showInputDialog("Enter Type (Income/Expense):");
    if (type == null) {
        return;
    }
    if (!("Income".equalsIgnoreCase(type) || "Expense".equalsIgnoreCase(type))) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid type entered! Please enter 'Income' or 'Expense'.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String description = javax.swing.JOptionPane.showInputDialog("Enter Description:");
    if (description == null) {
        return;
    }
    if (description.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Description cannot be empty!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String amountStr = javax.swing.JOptionPane.showInputDialog("Enter Amount:");
    if (amountStr == null) {
        return;
    }
    double amount;
    try {
        amount = Double.parseDouble(amountStr);
        if (amount <= 0) {
            throw new IllegalArgumentException();
        }
    } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid amount entered! Please enter a positive number.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String date = javax.swing.JOptionPane.showInputDialog("Enter Date (YYYY-MM-DD):");
    if (date == null) {
        return;
    }
    if (!isValidDate(date)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid date entered! Please use YYYY-MM-DD format and enter a valid date.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    com.mycompany.smartwallet_silvia.model.Transaction t =
        new com.mycompany.smartwallet_silvia.model.Transaction(
                type,
                amount,
                description,
                date
        );

com.mycompany.smartwallet_silvia.dao.TransactionDAO.add(t, userId);

loadTransactionsFromDB();
updateTotals();
    }//GEN-LAST:event_AddTransactionActionPerformed

    private boolean isValidDate(String date) {
        if (date == null || !date.matches("\\d{4}-\\d{2}-\\d{2}")) {
            return false;
        }
        String[] parts = date.split("-");
        int year = Integer.parseInt(parts[0]);
        int month = Integer.parseInt(parts[1]);
        int day = Integer.parseInt(parts[2]);
        if (month < 1 || month > 12) {
            return false;
        }
        int[] daysInMonth = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        if (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) {
            daysInMonth[1] = 29;
        }
        return day >= 1 && day <= daysInMonth[month - 1];
    }

    private void RemoveTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTransactionActionPerformed
     int selectedRow = Table.getSelectedRow();

    if (selectedRow != -1) {

        Integer id = rowToId.get(selectedRow);

        if (id == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Could not find transaction ID.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        com.mycompany.smartwallet_silvia.dao.TransactionDAO.delete(id);

        loadTransactionsFromDB();
        updateTotals();

    } else {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a transaction to remove.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_RemoveTransactionActionPerformed

    private javax.swing.table.DefaultTableModel originalModel;
    private java.util.Map<Integer, Integer> rowToId = new java.util.HashMap<>();
    
    private void ShowIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowIncomeActionPerformed
        filterTableByType("Income");
    }//GEN-LAST:event_ShowIncomeActionPerformed

    private void ShowExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowExpenseActionPerformed
        filterTableByType("Expense");
    }//GEN-LAST:event_ShowExpenseActionPerformed

    private void ShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllActionPerformed
        Table.setModel(originalModel);
    updateTotals();
    }//GEN-LAST:event_ShowAllActionPerformed

    private void FilterByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterByDateActionPerformed
         javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Table.getModel();

    ArrayList<Object[]> rows = new ArrayList<>();
    for (int i = 0; i < model.getRowCount(); i++) {
        Object[] row = new Object[model.getColumnCount()];
        for (int j = 0; j < model.getColumnCount(); j++) {
            row[j] = model.getValueAt(i, j);
        }
        rows.add(row);
    }

    rows.sort((row1, row2) -> {
        String dateStr1 = (String) row1[3];
        String dateStr2 = (String) row2[3];

        try {
            java.time.LocalDate date1 = java.time.LocalDate.parse(dateStr1);
            java.time.LocalDate date2 = java.time.LocalDate.parse(dateStr2);
            return date1.compareTo(date2);
        } catch (java.time.format.DateTimeParseException e) {
            System.err.println("Invalid date format: " + dateStr1 + " or " + dateStr2);
            return 0;
        }
    });

    javax.swing.table.DefaultTableModel sortedModel = new javax.swing.table.DefaultTableModel(
        new Object[][]{}, new String[]{"Type", "Description", "Amount", "Date"}
    );

    for (Object[] row : rows) {
        sortedModel.addRow(row);
    }

    Table.setModel(sortedModel);
    updateTotals();
    }//GEN-LAST:event_FilterByDateActionPerformed

    private void EditTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTransactionActionPerformed
        int selectedRow = Table.getSelectedRow();

    if (selectedRow != -1) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Table.getModel();

        String currentType = model.getValueAt(selectedRow, 0).toString();
        String currentDescription = model.getValueAt(selectedRow, 1).toString();
        String currentAmount = model.getValueAt(selectedRow, 2).toString();
        String currentDate = model.getValueAt(selectedRow, 3).toString();

        String newType = javax.swing.JOptionPane.showInputDialog(this, "Edit Type (Income/Expense):", currentType);
        if (newType == null || newType.trim().isEmpty()) return;

        if (!"Income".equalsIgnoreCase(newType) && !"Expense".equalsIgnoreCase(newType)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid type entered! Please enter 'Income' or 'Expense'.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String newDescription = javax.swing.JOptionPane.showInputDialog(this, "Edit Description:", currentDescription);
        if (newDescription == null || newDescription.trim().isEmpty()) return;

        String newAmountStr = javax.swing.JOptionPane.showInputDialog(this, "Edit Amount:", currentAmount);
        double newAmount;
        try {
            newAmount = Double.parseDouble(newAmountStr);
            if (newAmount <= 0) throw new IllegalArgumentException();
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid amount entered! Please enter a positive number.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String newDate = javax.swing.JOptionPane.showInputDialog(this, "Edit Date (YYYY-MM-DD):", currentDate);
        if (newDate == null || !isValidDate(newDate)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid date entered! Please use YYYY-MM-DD format and enter a valid date.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        model.setValueAt(newType, selectedRow, 0);
        model.setValueAt(newDescription, selectedRow, 1);
        model.setValueAt(String.format("%.2f", newAmount), selectedRow, 2);
        model.setValueAt(newDate, selectedRow, 3);

        updateTotals();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a transaction to edit.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_EditTransactionActionPerformed

    private void ShowChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowChartActionPerformed
    double income = 0;
    double expense = 0;

    for (int i = 0; i < originalModel.getRowCount(); i++) {

        String type = originalModel.getValueAt(i, 0).toString();
        double amount = Double.parseDouble(originalModel.getValueAt(i, 2).toString());

        if (type.equalsIgnoreCase("Income")) {
            income += amount;
        } else if (type.equalsIgnoreCase("Expense")) {
            expense += amount;
        }
    }

    org.jfree.data.category.DefaultCategoryDataset dataset =
            new org.jfree.data.category.DefaultCategoryDataset();

    dataset.addValue(income, "Amount", "Income");
    dataset.addValue(expense, "Amount", "Expense");

    org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createBarChart(
            "Wallet Overview",
            "Type",
            "Amount",
            dataset
    );

    org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);

    javax.swing.JFrame frame = new javax.swing.JFrame("Statistics");
    frame.setContentPane(chartPanel);
    frame.setSize(600, 400);
    frame.setLocationRelativeTo(this);
    frame.setVisible(true);
    }//GEN-LAST:event_ShowChartActionPerformed

    private void ConvertCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertCurrencyActionPerformed
        try {

    String fromCurrency = JOptionPane.showInputDialog(
            this,
            "Enter FROM currency:"
    );

    if (fromCurrency == null || fromCurrency.isEmpty()) return;
    fromCurrency = fromCurrency.toUpperCase();

    String toCurrency = JOptionPane.showInputDialog(
            this,
            "Enter TO currency:"
    );

    if (toCurrency == null || toCurrency.isEmpty()) return;
    toCurrency = toCurrency.toUpperCase();

    String amountStr = JOptionPane.showInputDialog(
            this,
            "Enter amount in " + fromCurrency + ":"
    );

    if (amountStr == null) return;

    double amount = Double.parseDouble(amountStr);

    URL url = new URL("https://open.er-api.com/v6/latest/" + fromCurrency);

    HttpURLConnection conn = (HttpURLConnection) url.openConnection();
    conn.setRequestMethod("GET");
    conn.connect();

    if (conn.getResponseCode() != 200) {
        JOptionPane.showMessageDialog(this, "API error");
        return;
    }

    StringBuilder sb = new StringBuilder();
    Scanner scanner = new Scanner(url.openStream());

    while (scanner.hasNext()) {
        sb.append(scanner.nextLine());
    }
    scanner.close();

    JSONObject json = new JSONObject(sb.toString());
    JSONObject rates = json.getJSONObject("rates");

    if (!rates.has(toCurrency)) {
        JOptionPane.showMessageDialog(this, "Invalid currency");
        return;
    }

    double rate = rates.getDouble(toCurrency);
    double converted = amount * rate;

    JOptionPane.showMessageDialog(
            this,
            String.format("%.2f %s = %.2f %s", amount, fromCurrency, converted, toCurrency)
    );

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error");
}
    }//GEN-LAST:event_ConvertCurrencyActionPerformed

     private void filterTableByType(String type) {
        javax.swing.table.DefaultTableModel filteredModel = new javax.swing.table.DefaultTableModel(
        new Object[][]{}, new String[]{"Type", "Description", "Amount", "Date"}
    );

    for (int i = 0; i < originalModel.getRowCount(); i++) {
        if (type.equalsIgnoreCase(originalModel.getValueAt(i, 0).toString())) {
            filteredModel.addRow(new Object[]{
                originalModel.getValueAt(i, 0),
                originalModel.getValueAt(i, 1),
                originalModel.getValueAt(i, 2),
                originalModel.getValueAt(i, 3)
            });
        }
    }

    Table.setModel(filteredModel);
    }
     
  private void loadTransactionsFromDB() {

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) Table.getModel();

    model.setRowCount(0);
    rowToId.clear();

    List<Transaction> list = TransactionDAO.getAll(userId);

    int rowIndex = 0;

    for (Transaction t : list) {

        model.addRow(new Object[]{
            t.getType(),
            t.getDescription(),
            String.format("%.2f", t.getAmount()),
            t.getDate()
        });

        rowToId.put(rowIndex, t.getId());
        rowIndex++;
    }

    updateTotals();
}


   private void updateTotals() {

    DefaultTableModel model =
            (DefaultTableModel) Table.getModel();

    double income = 0;
    double expense = 0;

    for (int i = 0; i < model.getRowCount(); i++) {

        String type = model.getValueAt(i, 0).toString();
        double amount = Double.parseDouble(model.getValueAt(i, 2).toString());

        if (type.equalsIgnoreCase("Income")) {
            income += amount;
        } else {
            expense += amount;
        }
    }

    Income.setText(String.format("Income: %.2f", income));
    Expense.setText(String.format("Expense: %.2f", expense));
    Total.setText(String.format("Total: %.2f", income - expense));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTransaction;
    private javax.swing.JButton ConvertCurrency;
    private javax.swing.JButton EditTransaction;
    private javax.swing.JTextField Expense;
    private javax.swing.JButton FilterByDate;
    private javax.swing.JTextField Income;
    private javax.swing.JButton RemoveTransaction;
    private javax.swing.JButton ShowAll;
    private javax.swing.JButton ShowChart;
    private javax.swing.JButton ShowExpense;
    private javax.swing.JButton ShowIncome;
    private javax.swing.JTable Table;
    private javax.swing.JTextField Total;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
